// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ee.ut.intime.domain;

import ee.ut.intime.domain.UsedTime;
import ee.ut.intime.domain.UsedTimeDataOnDemand;
import ee.ut.intime.domain.UsedTimeIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UsedTimeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: UsedTimeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UsedTimeIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: UsedTimeIntegrationTest: @Transactional;
    
    @Autowired
    UsedTimeDataOnDemand UsedTimeIntegrationTest.dod;
    
    @Test
    public void UsedTimeIntegrationTest.testCountUsedTimes() {
        Assert.assertNotNull("Data on demand for 'UsedTime' failed to initialize correctly", dod.getRandomUsedTime());
        long count = UsedTime.countUsedTimes();
        Assert.assertTrue("Counter for 'UsedTime' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UsedTimeIntegrationTest.testFindUsedTime() {
        UsedTime obj = dod.getRandomUsedTime();
        Assert.assertNotNull("Data on demand for 'UsedTime' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UsedTime' failed to provide an identifier", id);
        obj = UsedTime.findUsedTime(id);
        Assert.assertNotNull("Find method for 'UsedTime' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'UsedTime' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void UsedTimeIntegrationTest.testFindAllUsedTimes() {
        Assert.assertNotNull("Data on demand for 'UsedTime' failed to initialize correctly", dod.getRandomUsedTime());
        long count = UsedTime.countUsedTimes();
        Assert.assertTrue("Too expensive to perform a find all test for 'UsedTime', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<UsedTime> result = UsedTime.findAllUsedTimes();
        Assert.assertNotNull("Find all method for 'UsedTime' illegally returned null", result);
        Assert.assertTrue("Find all method for 'UsedTime' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UsedTimeIntegrationTest.testFindUsedTimeEntries() {
        Assert.assertNotNull("Data on demand for 'UsedTime' failed to initialize correctly", dod.getRandomUsedTime());
        long count = UsedTime.countUsedTimes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<UsedTime> result = UsedTime.findUsedTimeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'UsedTime' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'UsedTime' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UsedTimeIntegrationTest.testFlush() {
        UsedTime obj = dod.getRandomUsedTime();
        Assert.assertNotNull("Data on demand for 'UsedTime' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UsedTime' failed to provide an identifier", id);
        obj = UsedTime.findUsedTime(id);
        Assert.assertNotNull("Find method for 'UsedTime' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyUsedTime(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'UsedTime' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UsedTimeIntegrationTest.testMergeUpdate() {
        UsedTime obj = dod.getRandomUsedTime();
        Assert.assertNotNull("Data on demand for 'UsedTime' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UsedTime' failed to provide an identifier", id);
        obj = UsedTime.findUsedTime(id);
        boolean modified =  dod.modifyUsedTime(obj);
        Integer currentVersion = obj.getVersion();
        UsedTime merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'UsedTime' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UsedTimeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'UsedTime' failed to initialize correctly", dod.getRandomUsedTime());
        UsedTime obj = dod.getNewTransientUsedTime(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'UsedTime' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'UsedTime' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'UsedTime' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void UsedTimeIntegrationTest.testRemove() {
        UsedTime obj = dod.getRandomUsedTime();
        Assert.assertNotNull("Data on demand for 'UsedTime' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UsedTime' failed to provide an identifier", id);
        obj = UsedTime.findUsedTime(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'UsedTime' with identifier '" + id + "'", UsedTime.findUsedTime(id));
    }
    
}
