// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ee.ut.intime.domain;

import ee.ut.intime.domain.AppUserDataOnDemand;
import ee.ut.intime.domain.SubjectDataOnDemand;
import ee.ut.intime.domain.UsedTime;
import ee.ut.intime.domain.UsedTimeDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect UsedTimeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: UsedTimeDataOnDemand: @Component;
    
    private Random UsedTimeDataOnDemand.rnd = new SecureRandom();
    
    private List<UsedTime> UsedTimeDataOnDemand.data;
    
    @Autowired
    AppUserDataOnDemand UsedTimeDataOnDemand.appUserDataOnDemand;
    
    @Autowired
    SubjectDataOnDemand UsedTimeDataOnDemand.subjectDataOnDemand;
    
    public UsedTime UsedTimeDataOnDemand.getNewTransientUsedTime(int index) {
        UsedTime obj = new UsedTime();
        setHours(obj, index);
        setWorkDate(obj, index);
        return obj;
    }
    
    public void UsedTimeDataOnDemand.setHours(UsedTime obj, int index) {
        int hours = index;
        obj.setHours(hours);
    }
    
    public void UsedTimeDataOnDemand.setWorkDate(UsedTime obj, int index) {
        Date workDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setWorkDate(workDate);
    }
    
    public UsedTime UsedTimeDataOnDemand.getSpecificUsedTime(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        UsedTime obj = data.get(index);
        Long id = obj.getId();
        return UsedTime.findUsedTime(id);
    }
    
    public UsedTime UsedTimeDataOnDemand.getRandomUsedTime() {
        init();
        UsedTime obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return UsedTime.findUsedTime(id);
    }
    
    public boolean UsedTimeDataOnDemand.modifyUsedTime(UsedTime obj) {
        return false;
    }
    
    public void UsedTimeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = UsedTime.findUsedTimeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'UsedTime' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<UsedTime>();
        for (int i = 0; i < 10; i++) {
            UsedTime obj = getNewTransientUsedTime(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
