// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ee.ut.intime.domain;

import ee.ut.intime.domain.UsedTimeIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect UsedTimeIntegrationTest_Roo_Configurable {
    
    declare @type: UsedTimeIntegrationTest: @Configurable;
    
}
